import { describe, test, expect, beforeEach, afterEach } from "bun:test";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import {
  saveProfile,
  getProfile,
  listMembers,
  deleteMember,
  appendWorkLog,
  readWorkLog,
  type MemberProfile,
  type WorkLogEntry,
} from "../member-store.ts";

let tmpDir: string;
let membersDir: string;

beforeEach(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "member-test-"));
  membersDir = path.join(tmpDir, "members");
  fs.mkdirSync(membersDir, { recursive: true });
});

afterEach(() => {
  fs.rmSync(tmpDir, { recursive: true, force: true });
});

function makeProfile(overrides: Partial<MemberProfile> = {}): MemberProfile {
  return {
    uid: "test-uid-001",
    name: "alice",
    display_name: "Alice",
    role: "dev",
    type: "permanent",
    joined_at: "2024-01-01T00:00:00Z",
    ...overrides,
  };
}

describe("saveProfile / getProfile", () => {
  test("save and get profile", () => {
    const profile = makeProfile();
    saveProfile(membersDir, profile);
    const loaded = getProfile(membersDir, "alice");
    expect(loaded).not.toBeNull();
    expect(loaded!.uid).toBe("test-uid-001");
    expect(loaded!.name).toBe("alice");
    expect(loaded!.display_name).toBe("Alice");
    expect(loaded!.role).toBe("dev");
    expect(loaded!.type).toBe("permanent");
  });

  test("get profile returns null for nonexistent member", () => {
    const loaded = getProfile(membersDir, "ghost");
    expect(loaded).toBeNull();
  });

  test("profile without uid auto-generates one on read", () => {
    const profile = makeProfile();
    saveProfile(membersDir, profile);
    // Manually remove uid from the file
    const filePath = path.join(membersDir, "alice", "profile.json");
    const raw = JSON.parse(fs.readFileSync(filePath, "utf-8"));
    delete raw.uid;
    fs.writeFileSync(filePath, JSON.stringify(raw, null, 2), "utf-8");

    const loaded = getProfile(membersDir, "alice");
    expect(loaded).not.toBeNull();
    expect(loaded!.uid).toBeTruthy();
    // uid should be a valid UUID format (auto-generated by randomUUID)
    expect(loaded!.uid.length).toBeGreaterThan(10);

    // Should be persisted back to disk
    const reloaded = getProfile(membersDir, "alice");
    expect(reloaded!.uid).toBe(loaded!.uid);
  });
});

describe("listMembers", () => {
  test("returns all saved profiles", () => {
    saveProfile(membersDir, makeProfile({ name: "alice", uid: "uid-a" }));
    saveProfile(membersDir, makeProfile({ name: "bob", uid: "uid-b", display_name: "Bob" }));
    saveProfile(membersDir, makeProfile({ name: "carol", uid: "uid-c", display_name: "Carol" }));

    const members = listMembers(membersDir);
    expect(members.length).toBe(3);
    const names = members.map((m) => m.name).sort();
    expect(names).toEqual(["alice", "bob", "carol"]);
  });

  test("returns empty array for nonexistent dir", () => {
    const members = listMembers(path.join(tmpDir, "nonexistent"));
    expect(members).toEqual([]);
  });

  test("returns empty array for empty dir", () => {
    const emptyDir = path.join(tmpDir, "empty-members");
    fs.mkdirSync(emptyDir, { recursive: true });
    const members = listMembers(emptyDir);
    expect(members).toEqual([]);
  });
});

describe("deleteMember", () => {
  test("removes directory and returns true", () => {
    saveProfile(membersDir, makeProfile());
    expect(getProfile(membersDir, "alice")).not.toBeNull();

    const result = deleteMember(membersDir, "alice");
    expect(result).toBe(true);
    expect(getProfile(membersDir, "alice")).toBeNull();
    expect(fs.existsSync(path.join(membersDir, "alice"))).toBe(false);
  });

  test("returns false for nonexistent member", () => {
    const result = deleteMember(membersDir, "ghost");
    expect(result).toBe(false);
  });
});

describe("appendWorkLog / readWorkLog", () => {
  test("append and read work log", () => {
    const entry: WorkLogEntry = {
      event: "check_in",
      timestamp: "2024-01-01T10:00:00Z",
      project: "proj-a",
      task: "task-1",
    };
    appendWorkLog(membersDir, "alice", entry);
    const logs = readWorkLog(membersDir, "alice");
    expect(logs.length).toBe(1);
    expect(logs[0].event).toBe("check_in");
    expect(logs[0].project).toBe("proj-a");
    expect(logs[0].task).toBe("task-1");
  });

  test("read work log on nonexistent member returns empty array", () => {
    const logs = readWorkLog(membersDir, "ghost");
    expect(logs).toEqual([]);
  });

  test("multiple work log entries preserved in order", () => {
    const entries: WorkLogEntry[] = [
      { event: "check_in", timestamp: "2024-01-01T10:00:00Z", project: "proj-a", task: "task-1" },
      { event: "check_out", timestamp: "2024-01-01T12:00:00Z", project: "proj-a", note: "done" },
      { event: "check_in", timestamp: "2024-01-01T14:00:00Z", project: "proj-b", task: "task-2" },
    ];

    for (const entry of entries) {
      appendWorkLog(membersDir, "alice", entry);
    }

    const logs = readWorkLog(membersDir, "alice");
    expect(logs.length).toBe(3);
    expect(logs[0].event).toBe("check_in");
    expect(logs[0].project).toBe("proj-a");
    expect(logs[1].event).toBe("check_out");
    expect(logs[1].note).toBe("done");
    expect(logs[2].event).toBe("check_in");
    expect(logs[2].project).toBe("proj-b");
  });
});
